language: android
# Enable container-based infrastructure
sudo: false
android:
  components:
    - build-tools-22.0.1
    - android-22
    - extra-android-m2repository
branches:
  only:
    - master
before_install:
# Signature stub start
    - echo "stub keystore" > twizer.keystore
    - echo "stub storage pwd" > twizerstorage.pwd
    - echo "stub key pwd" > twizer.pwd
# Signature stub end
    - chmod +x ./gradlew
script:
    - ./gradlew clean assembleStandardTravis