package org.twizer.android.datamodel;

import com.google.gson.annotations.Expose;

import org.apache.commons.lang3.builder.EqualsBuilder;
import org.apache.commons.lang3.builder.HashCodeBuilder;
import org.apache.commons.lang3.builder.ToStringBuilder;

/**
 * Generated by jsonschema2pojo
 *
 * @author Jorge Antonio Diaz-Benito Soriano (github.com/Stoyicker).
 */
public final class Location {

    @Expose
    private String name;
    @Expose
    private Integer woeid;

    /**
     * @return The name
     */
    public String getName() {
        return name;
    }

    /**
     * @param name The name
     */
    public void setName(final String name) {
        this.name = name;
    }

    /**
     * @return The woeid
     */
    public Integer getWoeid() {
        return woeid;
    }

    /**
     * @param woeid The woeid
     */
    public void setWoeid(final Integer woeid) {
        this.woeid = woeid;
    }

    @Override
    public String toString() {
        return ToStringBuilder.reflectionToString(this);
    }

    @Override
    public int hashCode() {
        return new HashCodeBuilder().append(name).append(woeid).toHashCode();
    }

    @Override
    public boolean equals(final Object other) {
        if (other == this) {
            return true;
        }
        if ((other instanceof Location) == false) {
            return false;
        }
        Location rhs = ((Location) other);
        return new EqualsBuilder().append(name, rhs.name).append(woeid, rhs.woeid).isEquals();
    }

}