

package org.twizer.android.datamodel;

import com.google.gson.annotations.Expose;

import org.apache.commons.lang3.builder.EqualsBuilder;
import org.apache.commons.lang3.builder.HashCodeBuilder;
import org.apache.commons.lang3.builder.ToStringBuilder;

import java.util.ArrayList;
import java.util.List;

/**
 * Generated by jsonschema2pojo
 *
 * @author Jorge Antonio Diaz-Benito Soriano (github.com/Stoyicker).
 */
public final class TrendResultWrapper {

    @Expose
    private List<TrendWrapper> trends = new ArrayList<>();

    /**
     * @return The trends
     */
    public List<TrendWrapper> getTrends() {
        return trends;
    }

    @Override
    public String toString() {
        return ToStringBuilder.reflectionToString(this);
    }

    @Override
    public int hashCode() {
        return new HashCodeBuilder().append(trends).toHashCode();
    }

    @Override
    public boolean equals(final Object other) {
        if (other == this) {
            return Boolean.TRUE;
        }
        if (!(other instanceof TrendResultWrapper)) {
            return Boolean.FALSE;
        }
        TrendResultWrapper rhs = ((TrendResultWrapper) other);
        return new EqualsBuilder().append(trends, rhs.trends).isEquals();
    }

}
